//// <auto-generated />
//using MVSNChallenge.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace MVSNChallenge.Migrations
//{
//    [DbContext(typeof(UserContext))]
//    [Migration("20230408145346_INIT")]
//    partial class INIT
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.4")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("MVSNChallenge.Models.Compagnie", b =>
//                {
//                    b.Property<int>("ID")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

//                    b.Property<string>("DescrizioneCompagnia")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NomeCompagnia")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("ID");

//                    b.ToTable("Compagnie");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
